### PR TITLE
JSON serializer is fetched from Application env

### PR DESCRIPTION
**Pull request by arathunku**
in response to https://github.com/buren/chartkick-ex/pull/11#discussion_r247618720

Since this is a compile-time option, I didn't try to write tests for it. Should I add them and try to force recompile the module while running the tests? That might break some of the tests running concurrently, suggestions appreciated.

### CODE REVIEW

**Comment by buren** [comment]
I'm fine not having tests for that. Easy enough to test manually, should we later add more behavior like that it might be worth it.

Thank you 👍

**Comment by arathunku** [comment]
I've resolved conflicts with the master branch. 

Thank you for the library!

**Comment by buren** [comment]
@arathunku thank you 👍

**Comment by buren** [comment]
@arathunku just published [`v0.4.0` to hex.pm](https://hex.pm/packages/chartkick).

**Pull request merged**
